def add_footer(soup, root):
    root.append(soup.new_tag('br'))
    new_p = soup.new_tag('p')
    new_p.append('💎：如果这篇文章让你有所收获，欢迎')
    strong_tag = soup.new_tag('strong')
    strong_tag.append('点个在看👇')
    new_p.append(strong_tag)
    new_p.append('或者')
    strong_tag = soup.new_tag('strong')
    strong_tag.append('转发到朋友圈')
    new_p.append(strong_tag)
    new_p.append('，让更多人看到。')
    root.append(new_p)
